name       : wine
version    : 2.18
release    : 24
source     :
    - http://dl.winehq.org/wine/source/2.x/wine-2.19.tar.xz : 9f0931129878157d717cb39f16cd33bf49f40aac77331c93d0ad30f2ccac4f50
    - https://github.com/wine-compholio/wine-staging/archive/v2.19.tar.gz : 69c75d3ca17b1c3617cd0934a9e9ad6fca37c6679900d2cb63f6981aa1026cc8

license    : LGPL-2.1
component  : virt
summary    : Wine compatibility layer for Windows emulation.
description: |
    Wine (originally an acronym for "Wine Is Not an Emulator") is a compatibility layer capable of running Windows applications on several POSIX-compliant operating systems, such as Linux, Mac OSX, & BSD. Instead of simulating internal Windows logic like a virtual machine or emulator, Wine translates Windows API calls into POSIX calls on-the-fly, eliminating the performance and memory penalties of other methods and allowing you to cleanly integrate Windows applications into your desktop.
builddeps  :
    - pkgconfig(dri2proto)
    - pkgconfig(xproto)
    - pkgconfig32(alsa)
    - pkgconfig32(dbus-1)
    - pkgconfig32(d3d)
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(gl)
    - pkgconfig32(glu)
    - pkgconfig32(gnutls)
    - pkgconfig32(gtk+-2.0)
    - pkgconfig32(gtk+-3.0)
    - pkgconfig32(ice)
    - pkgconfig32(lcms2)
    - pkgconfig32(libdrm)
    - pkgconfig32(libgphoto2)
    - pkgconfig32(libmpg123)
    - pkgconfig32(libpng)
    - pkgconfig32(libpulse)
    - pkgconfig32(libtiff-4)
    - pkgconfig32(libv4l1)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(libxslt)
    - pkgconfig32(ocl-icd)
    - pkgconfig32(openal)
    - pkgconfig32(OpenCL)
    - pkgconfig32(x11)
    - pkgconfig32(xcb-dri3)
    - pkgconfig32(xcomposite)
    - pkgconfig32(xcursor)
    - pkgconfig32(xext)
    - pkgconfig32(xi)
    - pkgconfig32(xinerama)
    - pkgconfig32(xrandr)
    - pkgconfig32(xshmfence)
    - pkgconfig32(xxf86vm)
    - pkgconfig32(zlib)
    - cups-32bit-devel
    - glibc-32bit-devel
    - libgcc-32bit
    - libjpeg-turbo-32bit-devel
    - libpcap-32bit-devel
    - libpth-32bit-devel
    - ncurses-32bit-devel
    - openldap-32bit-devel
    - unixodbc-32bit-devel
patterns   :
    - 32bit :
        - /usr/bin/wine
rundeps    :
    - 32bit :
        - freetype2-32bit
        - harfbuzz-32bit
        - libgnutls-32bit
        - libp11-kit-32bit
        - libpng-32bit
        - libtiff-32bit
        - libtxc_dxtn-32bit
        - ncurses-32bit
setup      : |
    # D3D9 support
    %patch -p1 < $pkgfiles/d3d9-helper.patch
    %patch -p1 < $pkgfiles/wine-d3d9.patch

    autoreconf -vfi

    # Get 64-bit done first.
    mkdir wine64 && pushd wine64
    ../configure %CONFOPTS% --enable-win64 \
        --with-x
    %make
    popd
build      : |
    # 32-bit now
    mkdir wine32 && pushd wine32
    PKG_CONFIG_PATH=/usr/lib32/pkgconfig:/usr/share/pkgconfig:/usr/lib64/pkgconfig ../configure %CONFOPTS% --with-wine64=../wine64 \
        --libdir=/usr/lib32 \
        --with-x
    %make
    popd
install    : |
    pushd wine32
    %make_install
    popd

    pushd wine64
    %make_install
    popd

    # Font aliasing settings for Win32 applications
    install -d 755 $installdir/usr/share/fonts/conf.d
    install -d 755 $installdir/usr/share/fontconfig/conf.avail
    install -m 644 $pkgfiles/30-win32-aliases.conf $installdir/usr/share/fontconfig/conf.avail
    ln -s /usr/share/fontconfig/conf.avail/30-win32-aliases.conf $installdir/usr/share/fonts/conf.d/30-win32-aliases.conf

